name: Arkham-Alert
on:
  schedule:
    - cron:  '0 */6 * * *'        # alle 6 h (UTC)
  workflow_dispatch:              # manueller Start möglich
jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: python arkham_bot.py
        env:
          TG_TOKEN:   ${{ secrets.TG_TOKEN }}
          CHAT_ID:    ${{ secrets.CHAT_ID }}
          ARKHAM_KEY: ${{ secrets.ARKHAM_KEY }}   # noch leer → Script überspringt
